//! Offline IPv4 to country lookup, for placing a game server on the globe.
//!
//! Backed by `data/geo-ipv4.bin`, generated by
//! `infra/scripts/build-geo-ipv4.py` from DB-IP Lite (CC BY 4.0): every range
//! start as a little-endian u32, then one country index byte per range. DB-IP's
//! ranges are contiguous and sorted, so the starts alone identify the range an
//! address falls in - no end field needed.
//!
//! Precision is country level. That is deliberate: the globe renders at ~150px,
//! where a city centroid and a country centroid are the same dot.

use std::net::Ipv4Addr;

use crate::geo_countries::COUNTRIES;

const BLOB: &[u8] = include_bytes!("../data/geo-ipv4.bin");
const UNKNOWN: u8 = 255;

fn ranges() -> usize {
    BLOB.len() / 5
}

fn start(i: usize) -> u32 {
    let o = i * 4;
    u32::from_le_bytes([BLOB[o], BLOB[o + 1], BLOB[o + 2], BLOB[o + 3]])
}

fn code_index(i: usize) -> u8 {
    BLOB[ranges() * 4 + i]
}

/// Country code and representative point for an address, if known.
pub fn locate(ip: Ipv4Addr) -> Option<(&'static str, (f32, f32))> {
    let target = u32::from(ip);
    let n = ranges();
    if n == 0 || start(0) > target {
        return None;
    }
    // Largest index whose range start is at or below the address. The midpoint
    // rounds up, or an interval of two would never advance and this would spin.
    let (mut lo, mut hi) = (0usize, n - 1);
    while lo < hi {
        let mid = lo + (hi - lo).div_ceil(2);
        if start(mid) <= target {
            lo = mid;
        } else {
            hi = mid - 1;
        }
    }
    let c = code_index(lo);
    if c == UNKNOWN {
        return None;
    }
    let (code, lat, lon) = COUNTRIES[c as usize];
    Some((code, (lat, lon)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    fn addr(s: &str) -> Ipv4Addr {
        Ipv4Addr::from_str(s).unwrap()
    }

    #[test]
    fn resolves_well_known_public_addresses() {
        assert_eq!(locate(addr("8.8.8.8")).map(|(c, _)| c), Some("US"));
        assert_eq!(locate(addr("208.67.222.222")).map(|(c, _)| c), Some("US"));
    }

    #[test]
    fn resolves_outside_the_united_states() {
        // Guards the obvious wrong implementation: a lookup that answers "US"
        // to everything would pass the test above and fail here.
        let ru = locate(addr("77.88.8.8")).map(|(c, _)| c);
        assert_eq!(ru, Some("RU"), "Yandex DNS is Russia");
        assert_ne!(ru, Some("US"));
    }

    #[test]
    fn unknown_ranges_do_not_invent_a_position() {
        assert!(locate(addr("0.0.0.0")).is_none());
    }

    #[test]
    fn coordinates_are_on_the_planet() {
        for probe in ["8.8.8.8", "77.88.8.8", "80.80.80.80", "208.67.222.222"] {
            let (_, (lat, lon)) = locate(addr(probe)).expect("public address must resolve");
            assert!((-90.0..=90.0).contains(&lat), "{probe} latitude {lat}");
            assert!((-180.0..=180.0).contains(&lon), "{probe} longitude {lon}");
        }
    }

    #[test]
    fn range_starts_are_sorted_and_ascending() {
        let n = ranges();
        assert!(n > 100_000, "table looks truncated: {n} ranges");
        for i in 0..n - 1 {
            assert!(start(i) < start(i + 1), "starts unsorted at {i}");
        }
    }
}
