//! Embed the LightSpeed brand icon into the executable.
//!
//! Windows resolves the taskbar button, alt-tab entry, Explorer file icon and
//! shortcut icon from the **executable's own icon resource**. Calling
//! `ViewportBuilder::with_icon` at runtime only sends `WM_SETICON` for the
//! window the app already owns, so before this script existed the running
//! window had the brand mark while the taskbar button and every Explorer
//! surface showed Windows' generic default application icon.
//!
//! The icon is generated from the same `web/assets/brand/icon-256.png` the
//! window icon uses, so there is one source of truth for the brand mark. The
//! ICO is written into `OUT_DIR` rather than committed, which keeps the repo
//! free of a binary that would have to be regenerated by hand whenever the
//! tile changes.
//!
//! The compile step is delegated to whichever resource compiler the active
//! toolchain provides (`rc.exe` under MSVC, `windres` under GNU), so a plain
//! `cargo build` works on both without extra setup. A missing compiler is a
//! warning, not an error: the app is still perfectly usable without an exe
//! icon, and failing the build over cosmetics would be worse.
//!
//! Under the GNU linker this emits `warning: .rsrc merge failure: multiple
//! non-default manifests`. That warning is benign and the icon is unaffected -
//! verified by loading the built exe and finding RT_MANIFEST, RT_GROUP_ICON and
//! RT_ICON all present. rustc emits its own default manifest (because main.rs
//! sets `windows_subsystem = "windows"`) and GNU ld merges it with our icon
//! section, warning that it had to choose one. It still chooses, and the
//! runtime and shell both read the right resources.
//!
//! An earlier attempt removed the warning by renaming our section from `.rsrc`
//! to something else. That silenced it and BROKE the icon, because the PE
//! resource directory must be named exactly `.rsrc`; the built exe fell back to
//! the generic shell icon. The warning is therefore accepted over a fix that
//! trades a cosmetic build message for the actual defect this script exists to
//! solve.

use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Sizes Windows asks for by name. 256 is the modern shell icon; 16/32 are the
/// taskbar and title-bar sizes; 48 is used by Explorer's medium view.
const ICON_SIZES: [u32; 4] = [16, 32, 48, 256];

fn main() {
    println!("cargo:rerun-if-changed=../web/assets/brand/icon-256.png");
    println!("cargo:rerun-if-changed=build.rs");

    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let source = Path::new("../web/assets/brand/icon-256.png");

    let ico = match write_ico(source, &out_dir) {
        Ok(path) => path,
        Err(e) => {
            println!("cargo:warning=could not build the application icon: {e}");
            return;
        }
    };

    let rc = match write_rc(&out_dir, &ico) {
        Ok(path) => path,
        Err(e) => {
            println!("cargo:warning=could not write the icon resource script: {e}");
            return;
        }
    };

    if let Err(e) = compile_resource(&rc, &out_dir) {
        println!(
            "cargo:warning=no Windows resource compiler available, so the exe carries no icon: {e}"
        );
    }
}

/// Render the brand PNG into a multi-size ICO.
fn write_ico(source: &Path, out_dir: &Path) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let decoded = image::open(source)?.into_rgba8();
    let path = out_dir.join("lightspeed.ico");

    let mut frames = Vec::with_capacity(ICON_SIZES.len());
    for size in ICON_SIZES {
        let resized =
            image::imageops::resize(&decoded, size, size, image::imageops::FilterType::Lanczos3);
        frames.push(image::codecs::ico::IcoFrame::as_png(
            resized.as_raw(),
            size,
            size,
            image::ExtendedColorType::Rgba8,
        )?);
    }

    let file = std::fs::File::create(&path)?;
    let encoder = image::codecs::ico::IcoEncoder::new(std::io::BufWriter::new(file));

    // `encode_images` writes one directory entry per frame, which is what makes
    // Windows pick a crisp icon per context instead of downscaling the 256.
    encoder.encode_images(&frames)?;
    Ok(path)
}

/// Write the resource script that binds the ICO to the app's icon slots.
///
/// Only the icon is declared, as resource id 1. An earlier version also emitted
/// `1 24 "...ico"`, intending to add a manifest; type 24 is RT_MANIFEST, so that
/// line handed Windows the icon bytes *as a manifest*. GNU ld then merged two
/// manifests, produced a corrupt resource directory, and every binary failed to
/// start with "side-by-side configuration is incorrect" (error 14001). The
/// manifest is rustc's to emit; this script must not touch type 24.
fn write_rc(out_dir: &Path, ico: &Path) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let path = out_dir.join("lightspeed.rc");
    let escaped = ico.display().to_string().replace('\\', "\\\\");
    std::fs::write(&path, format!("1 ICON \"{escaped}\"\n"))?;
    Ok(path)
}

/// Compile the resource script into an object the linker will accept.
///
/// The two toolchains want different output flavours, and `.res` (MSVC) and
/// `.o` (GNU) are not interchangeable, so the extension is chosen to match the
/// compiler that actually ran.
fn compile_resource(rc: &Path, out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let msvc_res = out_dir.join("lightspeed.res");
    if try_rc(rc, &msvc_res)? {
        println!("cargo:rustc-link-arg={}", msvc_res.display());
        return Ok(());
    }

    let gnu_obj = out_dir.join("lightspeed-icon.o");
    try_windres(rc, &gnu_obj)?;
    println!("cargo:rustc-link-arg={}", gnu_obj.display());
    Ok(())
}

/// MSVC path: `rc.exe` produced by the Windows SDK.
fn try_rc(rc: &Path, out: &Path) -> Result<bool, Box<dyn std::error::Error>> {
    match Command::new("rc.exe")
        .args(["/nologo", "/fo"])
        .arg(out)
        .arg(rc)
        .status()
    {
        Ok(status) if status.success() => Ok(true),
        Ok(status) => Err(format!("rc.exe exited with {status}").into()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(e.into()),
    }
}

/// GNU path: `windres` from the MinGW toolchain, which the GNU target already
/// needs for linking.
fn try_windres(rc: &Path, out: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let candidates = ["windres", "x86_64-w64-mingw32-windres"];
    let mut last: Option<String> = None;

    for candidate in candidates {
        match Command::new(candidate)
            .arg(rc)
            .arg("-O")
            .arg("coff")
            .arg("-o")
            .arg(out)
            .status()
        {
            Ok(status) if status.success() => return Ok(()),
            Ok(status) => last = Some(format!("{candidate} exited with {status}")),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => continue,
            Err(e) => last = Some(format!("{candidate}: {e}")),
        }
    }

    Err(last
        .unwrap_or_else(|| "neither windres nor x86_64-w64-mingw32-windres is on PATH".into())
        .into())
}
