#!/usr/bin/env python3
"""Regenerate the offline IP-to-country tables used by the GUI globe.

Sources, both free and requiring no account:

  * Ranges -- DB-IP Lite (https://db-ip.com), CC BY 4.0. Monthly CSV.
  * Centroids -- the DSPL country list, one representative point per ISO code.

Writes two artefacts, both committed so a build never needs the network:

  * client-gui/data/geo-ipv4.bin  -- every IPv4 range start (u32, little
    endian) followed by the same number of country indices (u8). DB-IP's
    ranges are contiguous and sorted, so the starts alone are enough: the
    range containing an address is the last start at or below it.
  * client-gui/src/geo_countries.rs -- the index -> (code, lat, lon) table.

Usage:  python3 infra/scripts/build-geo-ipv4.py [--month YYYY-MM]
"""

import argparse
import csv
import gzip
import io
import os
import socket
import struct
import subprocess
import sys
import tempfile

RANGES_URL = "https://download.db-ip.com/free/dbip-country-lite-{month}.csv.gz"
CENTROIDS_URL = (
    "https://raw.githubusercontent.com/google/dspl/master/"
    "samples/google/canonical/countries.csv"
)

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BIN = os.path.join(REPO, "client-gui", "data", "geo-ipv4.bin")
TABLE = os.path.join(REPO, "client-gui", "src", "geo_countries.rs")

UNKNOWN = 255


def fetch(url: str, dest: str) -> None:
    subprocess.run(["curl", "-sL", "-m", "300", "-o", dest, url], check=True)
    if os.path.getsize(dest) == 0:
        sys.exit(f"empty download from {url}")


def ipv4(text: str) -> int | None:
    try:
        return struct.unpack(">I", socket.inet_aton(text))[0]
    except OSError:
        return None


def load_centroids(path: str) -> dict[str, tuple[float, float]]:
    out: dict[str, tuple[float, float]] = {}
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            try:
                out[row["country"].strip().upper()] = (
                    float(row["latitude"]),
                    float(row["longitude"]),
                )
            except (KeyError, ValueError):
                continue
    return out


def load_ranges(path: str) -> list[tuple[int, int, str]]:
    rows: list[tuple[int, int, str]] = []
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            p = line.strip().split(",")
            # IPv6 rows are skipped: game servers are reached over IPv4, and the
            # v6 table would triple the committed size for addresses the globe
            # will never plot.
            if len(p) < 3 or ":" in p[0] or ":" in p[1]:
                continue
            start, end = ipv4(p[0]), ipv4(p[1])
            if start is None or end is None:
                continue
            rows.append((start, end, p[2].upper()))
    rows.sort()
    for i in range(len(rows) - 1):
        if rows[i + 1][0] != rows[i][1] + 1:
            sys.exit(f"ranges are not contiguous at row {i}; starts are not enough")
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--month", default="2026-10", help="DB-IP release, YYYY-MM")
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        gz = os.path.join(tmp, "ranges.csv.gz")
        cen = os.path.join(tmp, "centroids.csv")
        fetch(RANGES_URL.format(month=args.month), gz)
        fetch(CENTROIDS_URL, cen)
        centroids = load_centroids(cen)
        rows = load_ranges(gz)

    # A range whose country has no centroid cannot be plotted, so it takes the
    # unknown slot rather than inventing a position.
    known = sorted({cc for (_, _, cc) in rows if cc in centroids})
    index = {cc: i for i, cc in enumerate(known)}
    if len(known) >= UNKNOWN:
        sys.exit(f"{len(known)} countries exceeds the u8 index space")

    os.makedirs(os.path.dirname(BIN), exist_ok=True)
    with open(BIN, "wb") as f:
        f.write(b"".join(struct.pack("<I", s) for s, _, _ in rows))
        f.write(bytes(index.get(cc, UNKNOWN) for _, _, cc in rows))

    with open(TABLE, "w", encoding="utf-8", newline="\n") as f:
        f.write("//! Generated by infra/scripts/build-geo-ipv4.py - do not edit.\n")
        f.write(f"//! Source: DB-IP Lite ({args.month}), CC BY 4.0.\n\n")
        f.write("/// Index -> (ISO 3166-1 alpha-2, representative latitude, longitude).\n")
        f.write(f"pub static COUNTRIES: [(&str, f32, f32); {len(known)}] = [\n")
        for cc in known:
            lat, lon = centroids[cc]
            f.write(f'    ("{cc}", {lat:.4}, {lon:.4}),\n')
        f.write("];\n")

    print(f"ranges      {len(rows)}")
    print(f"countries   {len(known)}")
    print(f"wrote       {BIN} ({os.path.getsize(BIN)} bytes)")
    print(f"wrote       {TABLE}")


if __name__ == "__main__":
    main()
