# LightSpeed Proxy Configuration
# Auto-generated by Terraform — do not edit manually.

[server]
node_id     = "${node_id}"
region      = "${region}"
max_clients = ${max_clients}

[security]
require_auth                = ${require_auth}
max_amplification_ratio     = ${max_amplification_ratio}
max_destinations_per_window = ${max_destinations_per_window}
ban_duration_secs           = ${ban_duration_secs}

[rate_limit]
max_pps_per_client = 1000
max_bps_per_client = 1000000
max_connections    = 200

[metrics]
enabled       = true
interval_secs = 10
